api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "discount-function-rs"
type = "function"
uid = "a1a9900e-8776-2411-a444-bf3a2aff01a7c360e941"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/discount-function-rs.wasm"
  watch = [ "src/**/*.rs" ]
