# [START discount-function-shopify.extension.api-version]
api_version = "2025-04"
# [END discount-function-shopify.extension.api-version]

# [START discount-function.toml.metadata]
[[extensions]]
name = "t:name"
handle = "discount-function-js"
type = "function"
description = "t:description"
# [END discount-function.toml.metadata]

# [START discount-function.toml.targets]
  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart-delivery-options-discounts-generate-run"
# [END discount-function.toml.targets]

# [START discount-function.toml.build]
  [extensions.build]
  command = ""
  path = "dist/function.wasm"
# [END discount-function.toml.build]
