[package]
# [START network-access.cargo-name]
name = "discount-function-rs"
# [END network-access.cargo-name]
version = "1.0.0"
edition = "2021"

[dependencies]
shopify_function = "1.1.0"

[dev-dependencies]
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 'z'
strip = true

