# [START discount-function-shopify.extension.api-version]
api_version = "2025-04"
# [END discount-function-shopify.extension.api-version]

# [START discount-function-shopify.extension.toml-metadata]
[[extensions]]
name = "t:name"
handle = "discount-function-rs"
type = "function"
description = "t:description"
# [END discount-function-shopify.extension.toml-metadata]

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

# [START discount-function.toml.targets]
  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.fetch"
  input_query = "src/cart_lines_discounts_generate_fetch.graphql"
  export = "cart_lines_discounts_generate_fetch"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.fetch"
  input_query = "src/cart_delivery_options_discounts_generate_fetch.graphql"
  export = "cart_delivery_options_discounts_generate_fetch"
# [END discount-function.toml.targets]

# [START discount-function-shopify.extension.toml-build]
  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/discount-function-rs.wasm"
  watch = [ "src/**/*.rs" ]
# [END discount-function-shopify.extension.toml-build]
