

# [START discount-function-shopify.extension.api-version]
api_version = "unstable"
# [END discount-function-shopify.extension.api-version]

# [START discount-function-shopify.extension.toml-metadata]
[[extensions]]
name = "t:name"
handle = "function-network-rust"
type = "function"
description = "t:description"
# [END discount-function-shopify.extension.toml-metadata]

  [[extensions.targeting]]
  target = "purchase.discount.cart_run"
  input_query = "src/generate_cart_run.graphql"
  export = "generate_cart_run"

  [[extensions.targeting]]
  target = "purchase.discount.delivery_run"
  input_query = "src/generate_delivery_run.graphql"
  export = "generate_delivery_run"

# [START discount-function.toml.targets]
  [[extensions.targeting]]
  target = "purchase.discount.cart_fetch"
  input_query = "src/generate_cart_fetch.graphql"
  export = "generate_cart_fetch"

  [[extensions.targeting]]
  target = "purchase.discount.delivery_fetch"
  input_query = "src/generate_delivery_fetch.graphql"
  export = "generate_delivery_fetch"
# [END discount-function.toml.targets]

# [START discount-function-shopify.extension.toml-build]
  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/function-rust.wasm"
  watch = [ "src/**/*.rs" ]
# [END discount-function-shopify.extension.toml-build]

[extensions.ui]
handle = "ui-extension-network-rs";