# [START discount-function-shopify.extension.api-version]
api_version = "unstable"
# [END discount-function-shopify.extension.api-version]

# [START discount-function-shopify.extension.toml-metadata]
[[extensions]]
name = "t:name"
handle = "function-network-js"
type = "function"
description = "t:description"
# [END discount-function-shopify.extension.toml-metadata]

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/generate_cart_run.graphql"
  export = "generate-cart-run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/generate_delivery_run.graphql"
  export = "generate-delivery-run"

# [START discount-function.toml.targets]
  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.fetch"
  input_query = "src/generate_cart_fetch.graphql"
  export = "generate-cart-fetch"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.fetch"
  input_query = "src/generate_delivery_fetch.graphql"
  export = "generate-delivery-fetch"
# [END discount-function.toml.targets]

# [START discount-function-shopify.extension.toml-build]
  [extensions.build]
  command = ""
  path = "dist/function.wasm"
# [END discount-function-shopify.extension.toml-build]


[extensions.ui]
handle = "ui-extension-network-js";