api_version = "2026-01"

[[extensions]]
# [START discount-function.name_and_description]
name = "t:name"
description = "t:description"
# [END discount-function.name_and_description]
handle = "discount-function-rs"
uid = "a1a9900e-8776-2411-a444-bf3a2aff01a7c360e941"

type = "function"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-wasip1/release/discount-function-rs.wasm"
  watch = [ "src/**/*.rs" ]

# [START discount-function.toml.metafield]
[extensions.input.variables]
namespace = "$app"
key = "function-configuration"
# [END discount-function.toml.metafield]

# [START discount-function.toml.ui]
[extensions.ui]
handle = "discount-ui-rs"
# [END discount-function.toml.ui]
