# This file stores configurations for your Shopify app.
# It must exist at the root of your app.
# [START discount-function.access-scopes]
scopes = "write_discounts"
# [END discount-function.access-scopes]

# [START discount-ui-extension-app.app_name]
name="Example Discount App"
# [END discount-ui-extension-app.app_name]

# [START discount-ui-extension.metafields-toml]
[discount.metafields.app.function-configuration]
type = "json"
name = "Function configuration"
access.admin = "merchant_read_write"
access.storefront = "none"
# [END discount-ui-extension.metafields-toml]
