# This file stores configurations for your Shopify app.
# It must exist at the root of your app.
# [START discount-function.access-scopes]
scopes = "write_discounts,read_products"
# [END discount-function.access-scopes]

# [START discount-ui-extension-app.app_name]
name="Example Discount App"
# [END discount-ui-extension-app.app_name]
