api_version = "2026-01"
[[extensions]]
# [START discount-ui-extension.name_and_description]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
# [END discount-ui-extension.name_and_description]
handle = "discount-ui-rs"
uid = "24b1f141-187f-bbd3-0951-77b73a219e9fc80af5c6"

type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
# [START discount-ui-extension.target-configuration]
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"
# [END discount-ui-extension.target-configuration]

# [START discount-ui-extension.metafields-toml]
[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"
# [END discount-ui-extension.metafields-toml]
