api_version = "2025-10"
[[extensions]]
# [START discount-ui-extension.name_and_description]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
# [END discount-ui-extension.name_and_description]
handle = "discount-ui-rs"
type = "ui_extension"
# Only 1 target can be specified for each Admin block extension
# [START discount-ui-extension.target-configuration]
[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"
# [END discount-ui-extension.target-configuration]

# [START discount-ui-extension.metafields-toml]
[[extensions.metafields]]
namespace = "$app:example-discounts--ui-extension"
key = "function-configuration"
# [END discount-ui-extension.metafields-toml]
