// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/api.js": {
    id: "routes/api";
    page: "/api";
  };
};
