api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "discount-function-js"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/generate_cart_run.graphql"
  export = "generate_cart_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/generate_delivery_run.graphql"
  export = "generate_delivery_run"

  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/discount-function.wasm"
  watch = [ "src/**/*.rs" ]

# [START discount-function.toml.metafield]
[extensions.input.variables]
namespace = "$app:example-discounts--ui-extension"
key = "function-configuration"
# [END discount-function.toml.metafield]

# [START discount-function.ui-paths]
[extensions.ui.paths]
create = "/app/discount/:functionId/new"
details = "/app/discount/:functionId/:id"
# [END discount-function.ui-paths]
